In [ ]:
import numpy as np

import pandas as pd
from google.colab import drive


drive.mount('/content/drive')
df=pd.read_csv('/content/drive/MyDrive/DNN-EdgeIIoT-dataset.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (2,3,6,11,13,14,15,16,17,31,32,34,39,45,51,54,55) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,frame.time,ip.src_host,ip.dst_host,arp.dst.proto_ipv4,arp.opcode,arp.hw.size,arp.src.proto_ipv4,icmp.checksum,icmp.seq_le,icmp.transmit_timestamp,...,mqtt.proto_len,mqtt.protoname,mqtt.topic,mqtt.topic_len,mqtt.ver,mbtcp.len,mbtcp.trans_id,mbtcp.unit_id,Attack_label,Attack_type
0,2021 11:44:10.081753000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
1,2021 11:44:10.162218000,192.168.0.101,192.168.0.128,0,0.0,0.0,0,0.0,0.0,0.0,...,4.0,MQTT,0,0.0,4.0,0.0,0.0,0.0,0,Normal
2,2021 11:44:10.162271000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
3,2021 11:44:10.162641000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
4,2021 11:44:10.166132000,192.168.0.101,192.168.0.128,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,Temperature_and_Humidity,24.0,0.0,0.0,0.0,0.0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2219196,2021 23:24:32.816050000,166.75.162.225,192.168.0.128,0,0.0,0.0,0,31814.0,45620.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219197,2021 23:24:32.816595000,70.162.34.183,192.168.0.128,0,0.0,0.0,0,27718.0,45636.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219198,2021 23:24:32.818043000,40.13.95.244,192.168.0.128,0,0.0,0.0,0,18502.0,45672.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219199,2021 23:24:32.820831000,18.132.75.125,192.168.0.128,0,0.0,0.0,0,1862.0,45737.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219200,2021 23:24:32.823654000,82.173.42.163,192.168.0.128,0,0.0,0.0,0,50245.0,45804.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP

In [ ]:
# Checking for NULL values
print('Null values in dataset are',len(df[df.isnull().any(1)]))
print('='*40)

# Checkng for DUPLICATE values
df.drop_duplicates(keep='first', inplace = True)

# For now, just drop NA's (rows with missing values)
df.dropna(inplace=True,axis=1)

print("Read {} rows.".format(len(df)))

Null values in dataset are 0
========================================
Read 2218386 rows.

In [ ]:
df.nunique()

frame.time            2206364
ip.src_host            137167
ip.dst_host             52426
arp.dst.proto_ipv4         10
arp.opcode                  3
                       ...
mbtcp.len                   8
mbtcp.trans_id            151
mbtcp.unit_id               6
Attack_label                2
Attack_type                15
Length: 63, dtype: int64

In [ ]:
high=[
"arp.hw.size",
"tcp.connection.synack",
"mqtt.conflag.cleansess",
"mqtt.topic_len",
"mqtt.ver",
"mqtt.conflags",
"http.response",
"tcp.connection.syn",
"mqtt.hdrflags",
"tcp.connection.rst",
"mqtt.msgtype",
"mqtt.len",
"http.content_length",
"tcp.flags.ack",
"tcp.ack_raw",
"tcp.len",
"tcp.checksum",
"ip.dst_host",
"tcp.seq",
"ip.src_host",
"tcp.payload",
"icmp.checksum",
"http.request.version",
"http.request.full_uri",
"http.referer",
"tcp.flags",
"http.request.method",
"http.file_data",
"tcp.ack",
"http.request.uri.query",
"icmp.seq_le" ,
"mqtt.msg",
"tcp.srcport" ,
"mqtt.conack.flags",
"mqtt.topic",
"tcp.dstport",
"mqtt.protoname",
"dns.qry.name.len",
"tcp.options"
     ]

In [ ]:
import ipaddress 

#converting IPv4 address to int 

def ip2int(ip):
  if ip=='0' or ip=='' or ip=='0.0' or ip==0.0 or ip==1.0 or ip==2.0:
        return 0
  else:
        return int(ipaddress.ip_address(ip))
#for ind in range(100000):
  #df['ip.dst_host'][ind]=ip2int(df['ip.dst_host'][ind])

In [ ]:
df.nunique()

frame.time            2206364
ip.src_host            137167
ip.dst_host             52426
arp.dst.proto_ipv4         10
arp.opcode                  3
                       ...
mbtcp.len                   8
mbtcp.trans_id            151
mbtcp.unit_id               6
Attack_label                2
Attack_type                15
Length: 63, dtype: int64

In [ ]:
ip_dst=[]
for ind in df['ip.dst_host'].index:
  ip_dst.append(ip2int(df['ip.dst_host'][ind]))
ip_src=[]
for ind in df['ip.src_host'].index:
  ip_src.append(ip2int(df['ip.src_host'][ind]))

In [ ]:
df.nunique()

frame.time            2206364
ip.src_host            137167
ip.dst_host             52426
arp.dst.proto_ipv4         10
arp.opcode                  3
                       ...
mbtcp.len                   8
mbtcp.trans_id            151
mbtcp.unit_id               6
Attack_label                2
Attack_type                15
Length: 63, dtype: int64

In [ ]:

from sklearn.preprocessing import LabelEncoder
 
#Create the function to fit and transform the label encoder
def label_encode_columns(df, columns):
    encoders = {}
    for col in columns:
        le = LabelEncoder().fit(df[col].astype('str'))
        df[col] = le.transform(df[col].astype('str'))
        encoders[col] = le
    return df, encoders

 
 
#Define the columns we want to encode
encode_columns=[
"tcp.payload",
"http.request.version",
"http.request.full_uri",
"http.referer",
"http.request.method",
"http.file_data",
"http.request.uri.query",
"mqtt.msg",
"mqtt.conack.flags",
"mqtt.topic",
"mqtt.protoname",
"dns.qry.name.len",
"tcp.options",
"tcp.srcport"
     ]
 
#Fit and transform the training dataset, returing both the new training dataset and the fitted encoders to use on the scoring dataset
df, encoders = label_encode_columns(df=df, columns=encode_columns)
df

,frame.time,ip.src_host,ip.dst_host,arp.dst.proto_ipv4,arp.opcode,arp.hw.size,arp.src.proto_ipv4,icmp.checksum,icmp.seq_le,icmp.transmit_timestamp,...,mqtt.proto_len,mqtt.protoname,mqtt.topic,mqtt.topic_len,mqtt.ver,mbtcp.len,mbtcp.trans_id,mbtcp.unit_id,Attack_label,Attack_type
0,2021 11:44:10.081753000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
1,2021 11:44:10.162218000,192.168.0.101,192.168.0.128,0,0.0,0.0,0,0.0,0.0,0.0,...,4.0,2,0,0.0,4.0,0.0,0.0,0.0,0,Normal
2,2021 11:44:10.162271000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
3,2021 11:44:10.162641000,192.168.0.128,192.168.0.101,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0,Normal
4,2021 11:44:10.166132000,192.168.0.101,192.168.0.128,0,0.0,0.0,0,0.0,0.0,0.0,...,0.0,0,2,24.0,0.0,0.0,0.0,0.0,0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2219196,2021 23:24:32.816050000,166.75.162.225,192.168.0.128,0,0.0,0.0,0,31814.0,45620.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219197,2021 23:24:32.816595000,70.162.34.183,192.168.0.128,0,0.0,0.0,0,27718.0,45636.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219198,2021 23:24:32.818043000,40.13.95.244,192.168.0.128,0,0.0,0.0,0,18502.0,45672.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219199,2021 23:24:32.820831000,18.132.75.125,192.168.0.128,0,0.0,0.0,0,1862.0,45737.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP
2219200,2021 23:24:32.823654000,82.173.42.163,192.168.0.128,0,0.0,0.0,0,50245.0,45804.0,0.0,...,0.0,1,1,0.0,0.0,0.0,0.0,0.0,1,DDoS_ICMP

In [ ]:
  x=df[high]

In [ ]:
#dummies = pd.get_dummies(df['Attack_type']) # Classification
#
#outcomes = dummies.columns
#num_classes = len(outcomes)
#print(outcomes)

def encode_text_dummy(df, name):

    dummies = pd.get_dummies(df[name])

    data=pd.DataFrame()

    for x in dummies.columns:

        dummy_name = f"{name}-{x}"

        data[dummy_name] = dummies[x]
    
    return data 

    #df.drop(name, axis=1, inplace=True)

y =  pd.DataFrame(encode_text_dummy(df, 'Attack_type'))

In [ ]:
y

,Attack_type-Backdoor,Attack_type-DDoS_HTTP,Attack_type-DDoS_ICMP,Attack_type-DDoS_TCP,Attack_type-DDoS_UDP,Attack_type-Fingerprinting,Attack_type-MITM,Attack_type-Normal,Attack_type-Password,Attack_type-Port_Scanning,Attack_type-Ransomware,Attack_type-SQL_injection,Attack_type-Uploading,Attack_type-Vulnerability_scanner,Attack_type-XSS
0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2219196,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2219197,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2219198,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2219199,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
2219200,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
x['ip.dst_host']=ip_dst
x['ip.src_host']=ip_src

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
for i in x:
    if x.dtypes[i]==np.float64:
        x[i] = np.asarray(x[i]).astype('float32')
x.info()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2218386 entries, 0 to 2219200
Data columns (total 39 columns):
 #   Column                  Dtype
---  ------                  -----
 0   arp.hw.size             float32
 1   tcp.connection.synack   float32
 2   mqtt.conflag.cleansess  float32
 3   mqtt.topic_len          float32
 4   mqtt.ver                float32
 5   mqtt.conflags           float32
 6   http.response           float32
 7   tcp.connection.syn      float32
 8   mqtt.hdrflags           float32
 9   tcp.connection.rst      float32
 10  mqtt.msgtype            float32
 11  mqtt.len                float32
 12  http.content_length     float32
 13  tcp.flags.ack           float32
 14  tcp.ack_raw             float32
 15  tcp.len                 float32
 16  tcp.checksum            float32
 17  ip.dst_host             int64
 18  tcp.seq                 float32
 19  ip.src_host             int64
 20  tcp.payload             int64
 21  icmp.checksum           float32
 22  http.request.version    int64
 23  http.request.full_uri   int64
 24  http.referer            int64
 25  tcp.flags               float32
 26  http.request.method     int64
 27  http.file_data          int64
 28  tcp.ack                 float32
 29  http.request.uri.query  int64
 30  icmp.seq_le             float32
 31  mqtt.msg                int64
 32  tcp.srcport             int64
 33  mqtt.conack.flags       int64
 34  mqtt.topic              int64
 35  tcp.dstport             float32
 36  mqtt.protoname          int64
 37  dns.qry.name.len        int64
 38  tcp.options             int64
dtypes: float32(23), int64(16)
memory usage: 482.4 MB

In [ ]:

from sklearn.preprocessing import StandardScaler

scale= StandardScaler()

scaled_data = scale.fit_transform(x) 
print(scaled_data)

[[-0.0514377   4.59305327 -0.19719503 ... -0.63135111 -0.59472012
   2.53324059]
 [-0.0514377  -0.2177201   5.0711218  ...  3.01213686 -0.59472012
  -0.44686552]
 [-0.0514377  -0.2177201  -0.19719503 ... -0.63135111 -0.59472012
  -0.44686552]
 ...
 [-0.0514377  -0.2177201  -0.19719503 ...  1.19039288  1.56368521
  -0.44685085]
 [-0.0514377  -0.2177201  -0.19719503 ...  1.19039288  1.56368521
  -0.44685085]
 [-0.0514377  -0.2177201  -0.19719503 ...  1.19039288  1.56368521
  -0.44685085]]

In [ ]:
X=pd.DataFrame(scaled_data)

In [ ]:
X.to_csv("data.csv",header=None, index= False)
y.to_csv("label.csv",header=None, index= False)

In [ ]:
data=pd.read_csv('data.csv')
lable=pd.read_csv('label.csv')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from tensorflow import keras
from keras import layers
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Embedding
from keras.callbacks import EarlyStopping
from keras.layers import LSTM, SimpleRNN, GRU
import numpy as np

x_tr, x_te, y_train, y_test = train_test_split(
    X, y, test_size=0.5, random_state=42)

#x_tra, x_val, y_train, y_val = train_test_split(
#    x_t, y_t, test_size=0.2, random_state=42)


#x_train = np.reshape(x_tr, (x_tr.shape[0], 1, x_tr.shape[1]))
#x_test = np.reshape(x_te, (1109193, 1, 40))

def build_model():
    model = keras.Sequential()
    #model.add(SimpleRNN(16,input_dim=data.shape[1], return_sequences=True))  # try using a GRU instead
    #model.add(Dropout(0.1))
    #model.add(SimpleRNN(16, return_sequences=True))  # try using a GRU instead
    #model.add(Dropout(0.1))
    #model.add(SimpleRNN(16, return_sequences=False))  # try using a GRU instead
    #model.add(Dropout(0.1))
    model.add(Dense(10))
    model.add(Activation('sigmoid'))
    model.add(Dense(100))
    model.add(Activation('sigmoid'))  
    
    model.add(layers.Dense(lable.shape[1], activation="softmax"))
  
    model.compile(
        optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"],
    )
    return model

model=build_model()
model.fit(x_tr,y_train,validation_data=(x_te,y_test),verbose=1,epochs=5)

NameError: ignored